<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
  </PropertyGroup>

<ItemGroup>
    <Content Include="..\resources\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
</ItemGroup>

<ItemGroup>
  <Content Remove="..\resources\assets\canjewelry\textures\item\resource\crochides\**" />
</ItemGroup>

<ItemGroup>
  <Content Remove="..\resources\assets\canjewelry\config\gemvisuals\shovel-steel-round.json" />
  <Content Remove="..\resources\assets\canjewelry\config\gemvisuals\shovel-steel.json" />
  <Content Remove="..\resources\assets\canjewelry\patches\canhavesockets\can-rock-drop-gems.json" />
  <Content Remove="..\resources\assets\canjewelry\patches\canhavesockets\can-ungraded-drop-gems.json" />
  <Content Remove="..\resources\assets\canjewelry\recipes\grid\transm_gems.json" />
  <Content Remove="..\resources\assets\canjewelry\shapes\item\bronze-gem-necklace - kopie.json" />
  <Content Remove="..\resources\assets\canjewelry\shapes\item\__rottenkingmask.json" />
  <Content Remove="..\resources\assets\game\patches\CB\can-add-cb.json" />
</ItemGroup>

<ItemGroup>
  <Reference Include="0Harmony">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Lib\0Harmony.dll</HintPath>
    <Private>False</Private>
  </Reference>
  <Reference Include="cairo-sharp">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Lib\cairo-sharp.dll</HintPath>
	  <Private>False</Private>
  </Reference>
  <Reference Include="Newtonsoft.Json">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Lib\Newtonsoft.Json.dll</HintPath>
	  <Private>False</Private>
  </Reference>
  <Reference Include="PlayerModelLib">
    <HintPath>..\..\..\..\..\libs\PlayerModelLib.dll</HintPath>
    <Private>False</Private>
  </Reference>
  <Reference Include="protobuf-net">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Lib\protobuf-net.dll</HintPath>
    <Private>False</Private>
  </Reference>
  <Reference Include="SkiaSharp">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Lib\SkiaSharp.dll</HintPath>
    <Private>False</Private>
  </Reference>
  <Reference Include="VintagestoryAPI">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\VintagestoryAPI.dll</HintPath>
	  <Private>False</Private>
  </Reference>
  <Reference Include="VintagestoryLib">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\VintagestoryLib.dll</HintPath>
	  <Private>False</Private>
  </Reference>
  <Reference Include="VSEssentials">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Mods\VSEssentials.dll</HintPath>
	  <Private>False</Private>
  </Reference>
  <Reference Include="VSSurvivalMod">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Mods\VSSurvivalMod.dll</HintPath>
	  <Private>False</Private>
  </Reference>
  <Reference Include="OpenTK.Graphics">
    <HintPath>..\..\..\..\..\AppData\Roaming\Vintagestory\Lib\OpenTK.Graphics.dll</HintPath>
    <Private>False</Private>
  </Reference>
</ItemGroup>

</Project>
